<a href="https://colab.research.google.com/github/aartis83/Airbnb_Clone/blob/master/Python_ABI_Module_2_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Analysis with Python

In this module we'll learn about data analysis with Python. We'll be using popular Python libraries like NumPy and Pandas. We will cover the following topics:

- Data structures from NumPy and Pandas
- Working with NumPy arrays
- Working with Pandas DataFrames
- Cleaning data
- Summarizing data
- Visualizing data


<img src='https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/187550926/original/cde47296f9d02346b6561eee753741d7272bfce6/do-data-analysis-in-python-using-numpy-pandas-matplotlib-seaborn.jpg' width=600>

# REMINDER - How to Take this Course

In this course, we will be learning programming and data analysis. These subjects involve theory and practice. The ABI program focuses on PRACTICE.
- Save a copy of this Notebook in your Drive
- Write and edit code in your Notebook
- Ask as many questions as you have (this is an intro course, there are NO dumb questions)
- Bring your own problems and ask questions on how to approach them (data analysis problem at work or school)

If you do not do these things, you will not retain much from this course. [Studies have shown](https://www.psychotactics.com/art-retain-learning/) that you retain:

- 75% of what you learn through practice
- 50% of what you learn through discussion with others
- 30% of what you learn through a demonstration
- 10% of what you learn from reading
- 5% of what you learn from a lecture

### Recommendations

* Learning Python requires context. **Experiment** with your creativity when learning it and use any search engine (Google, Bing, etc.) to explore the concept further with different examples.

* **Practice** makes perfect. When exploring a programming concept, try to test it with different approaches to understand what works and what does not and why it does so.

* Do not be afraid to **test the limits**. You can create a backup copy of this file and if anything goes wrong, you can always use the backup copy.


## Do you want to retain 75% of this course or 30%? The choice is yours.

---



# NumPy - Python's Numerical Library
---
<img src='https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1920px-NumPy_logo_2020.svg.png' width=600>

Python's standard library is quite limited when it comes to working with numbers. There were other languages more suited for that (FORTRAN, MATLAB, R). NumPy was created by Traphis Oliphant to help Python programmers have the same ability to work with arrays (collections) of numbers, also called matrices.

We won't do much with NumPy in this course beyond the basics. But it is important to understand them because they are the foundation for most data analysis in Python, even when we use other libraries. In fact, many data analysis libraries **rely** on NumPy to work!

<img src='https://predictivehacks.com/wp-content/uploads/2020/08/numpy_arrays-1024x572.png' width=600>

In [ ]:
import numpy as np

## Creating Arrays


### What is an Array?
The data that we analyze is almost always in the form of an array. The SQL database you query is a group of array. An Excel table is an array. A single row or single column is also an array. So what exactly are arrays?

Arrays are collections of data. In the context of Python, arrays are stored and interacted with using a library called NumPy:

A row in a table is an array (1 row, 5 columns)
A column in a table is an array (5 rows, 1 column)

### Are Sequences Arrays?
A Python list, tuple, string, dictionary can be considered an array in the general sense, but when we say 'array' in the context of Python programming, we are referring to NumPy arrays.

In [ ]:
# Creating an array is as simple as calling numpy:

array1 = np.array([1, 2, 3, 4])
array3 = np.array('string')

print(array1)
print(array3)

[1 2 3 4]
string


In [ ]:
# Faster ways to create array

array1 = np.arange(start=1, stop=10, step=2)
array2 = np.arange(start=10, stop=1, step=-1)

# An evenly spaced sequence in a specified interval
array3 = np.linspace(start=0, stop=10, num=6)

print('array1')
print(array1)
print('array2')
print(array2)
print('array3')
print(array3)

array1
[1 3 5 7 9]
array2
[10  9  8  7  6  5  4  3  2]
array3
[ 0.  2.  4.  6.  8. 10.]


In [ ]:
# Indexing a 1D array
array1 = np.array([4, 3, 8, 2])

# If we want the number 4, we use the index 0
print(array1[0])

# Second number
print(array1[1])

# Last number
print(array1[-1])

4
3
2


In [ ]:
# Slicing a 1D array
array1 = np.array([4, 3, 8, 2])

# Take the first 2 numbers
print(array1[0:2])

[4 3]


In [ ]:
# What about 2D arrays?

array1 = np.array([[1, 2, 3], [4, 5, 6]])

print('array1')
print(array1)
print('array1 info')
print('shape: ', np.shape(array1))
print('size: ', np.size(array1))

array1
[[1 2 3]
 [4 5 6]]
array1 info
shape:  (2, 3)
size:  6


In [ ]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]

list2d = [list1, list2]

array1 = np.array(list2d)

print(array1)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Fast 2D arrays
array1 = np.ones((2, 2))
array2 = np.zeros((2, 3))
array3 = np.eye(5)
array4 = np.diag([3, 4, 5])

print('array1')
print(array1)
print('array2')
print(array2)
print('array3')
print(array3)
print('array4')
print(array4)

array1
[[1. 1.]
 [1. 1.]]
array2
[[0. 0. 0.]
 [0. 0. 0.]]
array3
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
array4
[[3 0 0]
 [0 4 0]
 [0 0 5]]


In [ ]:
# Indexing 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])

print(array1)
print(array1[0])
print(array1[0, 1])
print(array1[:, 1])

[[1 2 3]
 [4 5 6]]
[1 2 3]
2
[2 5]


In [ ]:
# 1D arrays are by default shown as rows. You can have 2D arrays that are a single row or a single column
array1 = np.array([[1, 2, 3, 4, 5]])
array2 = np.array([[1], [2], [3], [4], [5]])

print(array1)
print(np.shape(array1))
print(array2)
print(np.shape(array2))

[[1 2 3 4 5]]
(1, 5)
[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


## Manipulating Arrays (Optional)

In [ ]:
# Reshape and resize an array
array1 = np.arange(0, 10, 1)
array2 = np.reshape(array1, (2,5))
array3 = np.reshape(array1, (5,2))

print('array1')
print(array1)
print('array2')
print(array2)
print('array3')
print(array3)

In [ ]:
# Transpose a 2D array
array1 = np.array([[1, 2], [3, 4]])
array2 = np.transpose(array1)

print(array1)
print('array2')
print(array2)

## Combining Arrays (Optional)

In [ ]:
# Putting arrays together
array1 = np.arange(0, 10, 1)
array2 = np.arange(10, 20, 1)
array3 = np.vstack((array1, array2))
array4 = np.hstack((array1, array2))

print('array3')
print(array3)
print('array4')
print(array4)

In [ ]:
# vstack and hstack using 2D arrays
array1 = np.zeros((3, 3))
array2 = np.ones((3, 3))
array3 = np.vstack((array1, array2))
array4 = np.hstack((array1, array2))

print('array3')
print(array3)
print('array4')
print(array4)

## Math with Arrays

In [ ]:
# edit - strongly typed

In [ ]:
# Math with one array
array1 = np.array([1, 2, 3, 4, 5])

print(array1)
print(array1 * 2)
print(array1 / 2)

[1 2 3 4 5]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [ ]:
# Math with two arrays (must be same size)
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([1, 1, 1, 1, 2])

print(array1)
print(array1 - array2)
print(array1 / array2)

[1 2 3 4 5]
[0 1 2 3 3]
[1.  2.  3.  4.  2.5]


## Conditional Indexing/Slicing

We have covered several ways to access data in arrays or sequences:
1. Know the key (dictionary)
2. Know the position (lists, arrays)

***However, conditional indexing is the most powerful way to index/slice data!***

Conditional indexing is specifying a **condition** instead of an index or key. Examples:
- Give me every number in this list that is greater than 10
- Give me every number in this array that is negative

We do this using the **conditional operators** we learned in Module 1.

In [ ]:
array1 = np.array([1, 2, 3, 4, 5])

print(array1[array1 > 2])
print(array1[array1 < 0])

[3 4 5]
[]


In [ ]:
# edit
# Exercise: Return the numbers in array1 greater than 1
print(array1[array1 > 1])

[2 3 4 5]


In [ ]:
# Exercise return the numbers in array1 equal to 4
array1[array1 == 4]

array([4])

## Editing NumPy Arrays (Optional)

In [ ]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = array1
array2[2] = 100

print(array1)
print(array2)

In [ ]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = array1.copy()
array2[2] = 100

print(array1)
print(array2)

## Generating Random Numbers (Optional)

In [ ]:
# random.randint

array1 = np.random.randint(0, 100, 20)
array2 = np.random.normal(loc=0, scale=2, size=10)

print(array1)
print(array2)

## Iterating with Arrays (Optional)

In [ ]:
# Iterating through arrays
# Purpose: want to do a complicated thing to each element
# not just multiply by 2
array1 = np.array([[1, 3, 4], [2, 4, 6], [10, 453, 40]])
print(array1)

print('')
print('print rows')
for row in array1:
    print('row: ', row)

print('')
print('enumerate')
for i, row in enumerate(array1):
    print('row: ', i, ' ', row)

In [ ]:
# Iterating with two arrays
array1 = np.array([[1, 3, 4], [2, 4, 6], [10, 453, 40]])
array2 = (array1**2).copy()

print('array1')
print(array1)
print('array2')
print(array2)

for i, j in zip(array1, array2):
    print('array1: ', i, 'array2: ', j)

# Pandas - Python's Data Analysis Library
---
<img src='https://raw.githubusercontent.com/earthinversion/earthinversion-images/main/images/pandas-python.png' width=600>

Pandas will be the most important library you learn in this course. It combines NumPy arrays with the concept of a DataFrame - a table of rows and columns - each with their own label. Pandas was developed to work with 1D and 2D (tabular) data.

Pandas DataFrames are more flexible than NumPy arrays (in 2D) because they can hold multiple data types, representing real data (i.e. names and ages). There are also many time saving functions (and methods) that are available.

The R language also uses DataFrames. Before Pandas, R had a clear advantage to data analysis over Python. However, when Pandas became mature, it equalized the power of R and Python for data analysis.

## An Example DataFrame

<img src='https://pynative.com/wp-content/uploads/2021/02/dataframe.png' width=600>

Note: a Series is one column from the DataFrame plus the index label.

The main differences between NumPy and Pandas are summarized below:
- DataFrames have index and column labels
- Pandas works in 1D (Series) or 2D (DataFrames), while NumPy can work in higher dimensions (3D, 100D, etc.)
- Pandas has more time-saving functions and methods (dealing with dates, filling missing data, aggregation, merging)
- Pandas can read and write from files easily, as well as from/to databases
- DataFrames can store multiple data types in ways that NumPy can't

## Why are Pandas DataFrames useful?
- Having index labels means you can refer to the same data even if it gets out of order (sorting)
- Column names are handy so you don't have to figure out what position each column is in
- You can do text operations on text, date operations on dates, numerical operations on numbers - all in the same DataFrame

## Pandas Series

A Pandas Series is actually similar to a Python dictionary in the sense that it has an index that can also behave as a key. However, it is designed for tabular data.

<img src='https://www.w3resource.com/w3r_images/pandas-series-add-image-1.svg' width=600>

In [ ]:
import pandas as pd

In [ ]:
series1 = pd.Series([3, 2, 0, 1])

print(series1)

0    3
1    2
2    0
3    1
dtype: int64


In [ ]:
print(series1.values)

[3 2 0 1]


In [ ]:
print(series1.index)

RangeIndex(start=0, stop=4, step=1)


In [ ]:
print(series1.name)

None


In [ ]:
ages = pd.Series(data=[3, 2, 0, 1], index=['Jim', 'Theo', 'Habib', 'Sachin'], name='Age')

ages

Jim       3
Theo      2
Habib     0
Sachin    1
Name: Age, dtype: int64

In [ ]:
print(ages.values)
print(ages.index)
print(ages.name)

[3 2 0 1]
Index(['Jim', 'Theo', 'Habib', 'Sachin'], dtype='object')
Age


**Indexing and Slicing Series**

<img src='https://i.ytimg.com/vi/nDAStujEjd4/maxresdefault.jpg' width=600>



In [ ]:
# Print Jim's age
print("Jim's age")
print(ages.loc['Jim'])
print(ages.iloc[0])

# Print the second person's age
print("Second person's age")
print(ages.loc['Theo'])
print(ages.iloc[1])

Jim's age
3
3
Second person's age
2
2


**You can also use conditional indexing in Pandas Series!**

In [ ]:
# Return the ages that are less than 3
ages.loc[ages < 3]

Theo      2
Habib     0
Sachin    1
Name: Age, dtype: int64

**Here's a quick way to return the first 5 data points from a Series!**

In [ ]:
ages = pd.Series(data=[3, 2, 0, 1, 2, 4, 6, 0],
                 index=['Jim', 'Theo', 'Habib', 'Sachin', 'James', 'Bob', 'Karen', 'Sophie'],
                 name='Age')

In [ ]:
ages

Jim       3
Theo      2
Habib     0
Sachin    1
James     2
Bob       4
Karen     6
Sophie    0
Name: Age, dtype: int64

In [ ]:
# Typical notation: head(ages)
# Method notation: ages.head()

In [ ]:
# First 5 data points
ages.head()

Jim       3
Theo      2
Habib     0
Sachin    1
James     2
Name: Age, dtype: int64

In [ ]:
# Last 5 data points
ages.tail()

Sachin    1
James     2
Bob       4
Karen     6
Sophie    0
Name: Age, dtype: int64

**Practice: Return the name of the newborn(s)**

In [ ]:
# Your code here (hint: use conditional indexing then use .index)
ages.loc[ages==0]

Habib     0
Sophie    0
Name: Age, dtype: int64

## Pandas DataFrames
As we have shown above, Pandas DataFrames have columns, an index, and tabular data.

Another way to think about pandas DataFrames is a bunch of Series with the same index, put together into one package.

### What is a Series?
A pandas Series is like a DataFrame but it only has one column. So it has an index, a column name, the column data, and that's it. You can combine multiple Series (with the same index) to create a DataFrame.

When you look at each column in a DataFrame, it is actually a Series!

<img src='https://storage.googleapis.com/lds-media/images/series-and-dataframe.width-1200.png' width=500>

In [ ]:
array1 = np.array([[1, 2, 5], [3, 5, 6]])
print(array1)

[[1 2 5]
 [3 5 6]]


In [ ]:
# Dataframes accept arrays or lists or array-like inputs
df1 = pd.DataFrame(data=array1,
                   index=['Index One', 'Index Two'],
                   columns=['Col 1', 'Col 2', 'Col 3'])

print(df1)

           Col 1  Col 2  Col 3
Index One      1      2      5
Index Two      3      5      6


In [ ]:
# Let's avoid using Print when displaying DataFrames (Colab Notebook renders it better)
df1

Col 1  Col 2  Col 3
Index One      1      2      5
Index Two      3      5      6

**Pandas DataFrames have columns, data, and an index**

In [ ]:
df1.columns

Index(['Col 1', 'Col 2', 'Col 3'], dtype='object')

In [ ]:
df1.index

Index(['Index One', 'Index Two'], dtype='object')

In [ ]:
df1.values

array([[1, 2, 5],
       [3, 5, 6]])

In [ ]:
# Let's return a specific column by name.
df1['Col 1']

Index One    1
Index Two    3
Name: Col 1, dtype: int64

In [ ]:
# Does that look familiar? It's a series!
type(df1['Col 1'])

pandas.core.series.Series

In [ ]:
# Let's return a specific row by the index label.
df1.loc['Index Two']

Col 1    3
Col 2    5
Col 3    6
Name: Index Two, dtype: int64

In [ ]:
# Wait a minute, that also looks like a series!
type(df1.loc['Index Two'])

pandas.core.series.Series

In [ ]:
# Let's return a specific row by position.
df1.iloc[1]

Col 1    3
Col 2    5
Col 3    6
Name: Index Two, dtype: int64

In [ ]:
# Let's return a specific row and column
df1.loc['Index One', 'Col 1']

1

In [ ]:
# Challenge - return value from second index and third column
df1.loc['Index Two', 'Col 3']

6

In [ ]:
# Each series contains a value, an array and an index
print(df1['Col 1'].name)
print(df1['Col 1'].values)
print(df1['Col 1'].index)

Col 1
[1 3]
Index(['Index One', 'Index Two'], dtype='object')


In [ ]:
# Every column (pandas Series) has the same index, which is the DataFrame's Index
print(df1.index)
print(df1['Col 1'].index)
print(df1['Col 2'].index)

Index(['Index One', 'Index Two'], dtype='object')
Index(['Index One', 'Index Two'], dtype='object')
Index(['Index One', 'Index Two'], dtype='object')


***The values inside of a Pandas DataFrame or a Pandas Series are numpy arrays!***

In [ ]:
print(df1.values)
print(type(df1.values))
print(type(df1['Col 1'].values))

[[1 2 5]
 [3 5 6]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
# Babies example
children = pd.DataFrame(data=[[3, 10], [2, 15], [0, 5], [1, 20], [2, 16], [4, 30], [6, 40], [0, 7]],
                 index=['Jim', 'Theo', 'Habib', 'Sachin', 'James', 'Bob', 'Karen', 'Sophie'],
                 columns=['Ages', 'Weights'])

children

Ages  Weights
Jim        3       10
Theo       2       15
Habib      0        5
Sachin     1       20
James      2       16
Bob        4       30
Karen      6       40
Sophie     0        7

In [ ]:
children.loc[children['Ages'] == 0]

Ages  Weights
Habib      0        5
Sophie     0        7

In [ ]:
children.loc[children['Weights'] < 10]

Ages  Weights
Habib      0        5
Sophie     0        7

In [ ]:
# Challenge: Children between the ages of 1 and 5 (inclusive)
# Hint: two steps with an intermediate variable
children.loc[children['Ages'] >= 1].loc[children['Ages'] <= 5]

Ages  Weights
Jim        3       10
Theo       2       15
Sachin     1       20
James      2       16
Bob        4       30

**More Info on Indexing and Slicing**

<img src='https://python.astrotech.io/_images/pandas-dataframe-select-row.png' width=600>

<img src='https://i0.wp.com/sparkbyexamples.com/wp-content/uploads/2021/10/pandas-difference-loc-vs-iloc.png?resize=840%2C353&ssl=1' width=600>

**We can also use .head() and .tail() on Pandas DataFrames!**

In [ ]:
# First 5 rows
children.head()

Ages  Weights
Jim        3       10
Theo       2       15
Habib      0        5
Sachin     1       20
James      2       16

In [ ]:
# Last 5 rows
children.tail()

Ages  Weights
Sachin     1       20
James      2       16
Bob        4       30
Karen      6       40
Sophie     0        7

In [ ]:
# Retrieving columns
children['Ages']

Jim       3
Theo      2
Habib     0
Sachin    1
James     2
Bob       4
Karen     6
Sophie    0
Name: Ages, dtype: int64

In [ ]:
children.loc['Theo', 'Weights']

15

In [ ]:
# Example
# Age of bob
children.loc['Bob', 'Ages']

4

## Melting and Pivoting (Optional)

**Melted vs Pivoted Data**


**Melting Data**

<img src='https://pandas.pydata.org/pandas-docs/dev/_images/reshaping_melt.png' width=600>

**Pivoting Data - We're going to Pivot this data!**

<img src='https://pandas.pydata.org/pandas-docs/dev/_images/reshaping_pivot.png' width=600>

## Adding/Removing Rows or Columns (Optional)

In [ ]:
# Let's add a column
df1['Words'] = ['Hello', 'World']

df1

In [ ]:
# Let's delete a column
del df1['Words']
df1

In [ ]:
# Let's create a new column from existing columns
df1['Sum'] = df1['Col 1'] + df1['Col 2']

df1

In [ ]:
# Let's add a row
add_row = pd.Series([4, 5, 6, 15], index=['Col 1', 'Col 2', 'Col 3', 'Sum'],
                    name='Index Three')

df2 = df1.append(add_row)
df2

In [ ]:
# Let's remove a row
df2 = df1.drop('Index One')

In [ ]:
df2

## Iterating with Pandas (Optional)

In [ ]:

# .map
# .apply
# .apply with lambda


## Time Functions in Pandas (Optional)

In [ ]:
# Timestamp
# DatetimeIndex
# Timedelta
# date_range
# .weekday

## Importing and Exporting Data
Pandas has functions that can read from and write to:
- Excel files (pd.read_excel) (df.to_excel)
- Comma separated files (pd.read_csv) (df.to_csv)
- JSON files (pd.read_json) (df.to_json)
- HTML files (pd.read_html) (df.to_html)
- Databases (pd.read_sql) (df.to_sql)

<img src='https://files.realpython.com/media/Reading-and-Writing-Data-With-Pandas_Watermarked.435ef1c38466.jpg' width=600>

In [ ]:
# Read table from webpage
url_wc = 'https://en.wikipedia.org/wiki/25th_Arabian_Gulf_Cup'

world_cup_finals = pd.read_html(url_wc)

In [ ]:
type(world_cup_finals)

list

In [ ]:
world_cup_finals[4]

0  \
0  Referees  Ma Ning  Ali Sabah  Abdullah Jamali ...   

                                                   1  \
0  Assistant Referees  Zhang Cheng  Zhou Fei  Ras...   

                                                   2  
0  Video Assistant Referees  Fu Ming  Mohanad Qas...

In [ ]:
world_cup_finals[1]  # Try 0, 1, 2, 3

Team Appearance  \
                   Team Appearance   
0                 Qatar       25th   
1          Saudi Arabia       24th   
2          Iraq (hosts)       16th   
3  United Arab Emirates       24th   
4                  Oman       23rd   
5     Bahrain (holders)       25th   
6                Kuwait       25th   
7                 Yemen       10th   

                            Previous bestperformance FIFA Rankings  \
                            Previous bestperformance  October 2022   
0                         Winners (1992, 2004, 2014)            50   
1                      Winners (1994, 2002, 2003–04)            51   
2                         Winners (1979, 1984, 1988)            68   
3                               Winners (2007, 2013)            70   
4                            Winners (2009, 2017–18)            75   
5                                     Winners (2019)            85   
6  Winners (1970, 1972, 1974, 1976, 1982, 1986, 1...           149   
7  Group stage (2003–04, 2004, 2007, 2009, 2010, ...           155   

                      
  Unnamed: 4_level_1  
0                NaN  
1                NaN  
2                NaN  
3                NaN  
4                NaN  
5                NaN  
6                NaN  
7                NaN

In [ ]:
world_cup_finals_list = world_cup_finals[1]

world_cup_finals_list.head()

Team Appearance       Previous bestperformance  \
                   Team Appearance       Previous bestperformance   
0                 Qatar       25th     Winners (1992, 2004, 2014)   
1          Saudi Arabia       24th  Winners (1994, 2002, 2003–04)   
2          Iraq (hosts)       16th     Winners (1979, 1984, 1988)   
3  United Arab Emirates       24th           Winners (2007, 2013)   
4                  Oman       23rd        Winners (2009, 2017–18)   

  FIFA Rankings                     
   October 2022 Unnamed: 4_level_1  
0            50                NaN  
1            51                NaN  
2            68                NaN  
3            70                NaN  
4            75                NaN

In [ ]:
world_cup_finals_list.tail()

Team Appearance  \
                   Team Appearance   
3  United Arab Emirates       24th   
4                  Oman       23rd   
5     Bahrain (holders)       25th   
6                Kuwait       25th   
7                 Yemen       10th   

                            Previous bestperformance FIFA Rankings  \
                            Previous bestperformance  October 2022   
3                               Winners (2007, 2013)            70   
4                            Winners (2009, 2017–18)            75   
5                                     Winners (2019)            85   
6  Winners (1970, 1972, 1974, 1976, 1982, 1986, 1...           149   
7  Group stage (2003–04, 2004, 2007, 2009, 2010, ...           155   

                      
  Unnamed: 4_level_1  
3                NaN  
4                NaN  
5                NaN  
6                NaN  
7                NaN

In [ ]:
world_cup_finals_list.columns = ['Team', 'Appearance', 'Previous Best Performance', 'FIFA Ranking', 'Dummy']
world_cup_finals_list

Team Appearance  \
0                 Qatar       25th   
1          Saudi Arabia       24th   
2          Iraq (hosts)       16th   
3  United Arab Emirates       24th   
4                  Oman       23rd   
5     Bahrain (holders)       25th   
6                Kuwait       25th   
7                 Yemen       10th   

                           Previous Best Performance  FIFA Ranking  Dummy  
0                         Winners (1992, 2004, 2014)            50    NaN  
1                      Winners (1994, 2002, 2003–04)            51    NaN  
2                         Winners (1979, 1984, 1988)            68    NaN  
3                               Winners (2007, 2013)            70    NaN  
4                            Winners (2009, 2017–18)            75    NaN  
5                                     Winners (2019)            85    NaN  
6  Winners (1970, 1972, 1974, 1976, 1982, 1986, 1...           149    NaN  
7  Group stage (2003–04, 2004, 2007, 2009, 2010, ...           155    NaN

In [ ]:
world_cup_finals_list['Team']

0                   Qatar
1            Saudi Arabia
2            Iraq (hosts)
3    United Arab Emirates
4                    Oman
5       Bahrain (holders)
6                  Kuwait
7                   Yemen
Name: Team, dtype: object

In [ ]:
from google.colab import files  # need this to work with files in colab

world_cup_finals_list.to_csv('world_cup_finals.csv')

files.download('world_cup_finals.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

### Student Examples (Optional)

**Practice - Find a table on Wikipedia and read it into a Pandas DataFrame**

In [ ]:
practice = 'https://en.wikipedia.org/wiki/2021%E2%80%932023_inflation_surge'
result = pd.read_html(practice)[1]
result

Country/Region  2020   2021 Aug 2022
0                     World  1.9%   3.4%       8%
1       Europe/Central Asia  1.2%   3.1%     9.1%
2   Latin America/Caribbean  1.4%   4.3%     9.9%
3                    Brazil  3.2%   8.3%     8.8%
4                South Asia  5.7%   5.5%     4.5%
5                 Australia  0.8%   2.9%     7.8%
6               South Korea  0.5%   2.5%     5.6%
7                     Japan  0.0%  -0.2%       3%
8                     China  2.4%   1.0%     2.3%
9                    Canada  0.7%   3.4%     7.6%
10           United Kingdom  1.0%   2.5%     9.9%
11            United States  1.2%   4.7%     8.2%

# Cleaning Data

Python (+Pandas) excels at cleaning data. Note from day 1 that one of the main reasons to use Python over other tools is having a dirty dataset. While SQL can take you far with data cleaning, Python's syntax is much more readable and traceable - you can clearly see and describe all of your data cleaning steps.

When data is first collected, it is called "raw" data. Examples are temperature sensors, survey forms (SurveyMonkey), cameras, and so on. In nearly 100% of cases, data cleaning is required. This involves the following:
- Filling in missing data
- Recognizing bad (erroneous) data and fixing it
- Transforming the data into something easier to analyze (removing capitals from text, changing units from feet to meters, calculating percents, etc.)

In some organizations, the data analyst does minimal data cleaning. That is because the data team (data engineers, database administrators) takes care of it before it gets to you for analysis. This process is called **Data Ops** and requires constant work to maintain quality, reliable, analyzable data. In a perfect world, every organization would have a mature **Data Ops** practice and the analysts would focus on analysis. However, in reality...

***I have never worked at an organization where I didn't have to do data cleaning on a semi-regular basis.***

In [ ]:
import pandas as pd

In [ ]:
our_example_dataframe = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
                   "toy": [None, 'Batmobile', 'Bullwhip'],
                   "born": [None, '1940', None]})
our_example_dataframe

name        toy  born
0    Alfred       None  None
1    Batman  Batmobile  1940
2  Catwoman   Bullwhip  None

Delete all rows that have null values in any column.

In [ ]:
our_example_dataframe.dropna()

name        toy  born
1  Batman  Batmobile  1940

Delete rows based on null values from one column.

In [ ]:
our_example_dataframe.dropna(subset=['toy'])

name        toy  born
1    Batman  Batmobile  1940
2  Catwoman   Bullwhip  None

**Practice - drop rows based on null values in the 'born' column**

In [ ]:
# Your code here
our_example_dataframe.dropna(subset=['born'])

name        toy  born
1  Batman  Batmobile  1940

Fill all null values with a replacement value

In [ ]:
our_example_dataframe.fillna('1930')

name        toy  born
0    Alfred       1930  1930
1    Batman  Batmobile  1940
2  Catwoman   Bullwhip  1930

In [ ]:
# our_example_dataframe

In [ ]:
our_example_dataframe['born'] = our_example_dataframe['born'].fillna('1930')
our_example_dataframe['toy'] = our_example_dataframe['toy'].fillna('Necktie')
our_example_dataframe

name        toy  born
0    Alfred    Necktie  1930
1    Batman  Batmobile  1940
2  Catwoman   Bullwhip  1930

Set the index to the name, so that we can use it as a handy index label

In [ ]:
df2 = our_example_dataframe.set_index('name')

df2

toy  born
name                     
Alfred      Necktie  1930
Batman    Batmobile  1940
Catwoman   Bullwhip  1930

In [ ]:
df2.index

Index(['Alfred', 'Batman', 'Catwoman'], dtype='object', name='name')

In [ ]:
df2.loc['Alfred']

toy     Necktie
born       1930
Name: Alfred, dtype: object

In [ ]:
df2.iloc[0]

toy     Necktie
born       1930
Name: Alfred, dtype: object

In [ ]:
df2.columns

Index(['toy', 'born'], dtype='object')

If you don't like the index, you can reset the index

In [ ]:
df2.reset_index()

name        toy  born
0    Alfred    Necktie  1930
1    Batman  Batmobile  1940
2  Catwoman   Bullwhip  1930

Make a copy of the DataFrame so that any further changes only save to the copy of the DataFrame

In [ ]:
df3 = df2.copy()

# Adding a column
df3['Fav Color'] = ['Gray', 'Black', 'Midnight']
df3

toy  born Fav Color
name                               
Alfred      Necktie  1930      Gray
Batman    Batmobile  1940     Black
Catwoman   Bullwhip  1930  Midnight

In [ ]:
df2  # unchanged

toy  born
name                     
Alfred      Necktie  1930
Batman    Batmobile  1940
Catwoman   Bullwhip  1930

In [ ]:
df3.index = ['One', 'Two', 'Three']
df3

toy  born Fav Color
One      Necktie  1930      Gray
Two    Batmobile  1940     Black
Three   Bullwhip  1930  Midnight

In [ ]:
df3.index

Index(['One', 'Two', 'Three'], dtype='object')

# Summarizing Data

Summarizing data is very useful in data exploration, also known as exploratory data analysis (EDA).

We will look at different ways to summarize data such as:
- Aggregating data
- Summary statistics
- Displaying unique values in the data


In [ ]:
df = pd.DataFrame({
    'brand': ['Yum Yum', 'Yum Yum', 'Indomie', 'Indomie', 'Indomie'],
    'style': ['cup', 'cup', 'cup', 'pack', 'pack'],
    'rating': [4, 4, 3.5, 5, 5]})

df

brand style  rating
0  Yum Yum   cup     4.0
1  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack     5.0
4  Indomie  pack     5.0

In [ ]:
df.describe(include='all')

brand style   rating
count         5     5  5.00000
unique        2     2      NaN
top     Indomie   cup      NaN
freq          3     3      NaN
mean        NaN   NaN  4.30000
std         NaN   NaN  0.67082
min         NaN   NaN  3.50000
25%         NaN   NaN  4.00000
50%         NaN   NaN  4.00000
75%         NaN   NaN  5.00000
max         NaN   NaN  5.00000

In [ ]:
df['rating'].sum()

21.5

In [ ]:
df['rating'].min()

3.5

In [ ]:
df['rating'].mean()

4.3

In [ ]:
df['rating'].median()

4.0

## Display Unique Values (SELECT DISTINCT)

Display the unique values in a column. This gives you a good sense of what kind of data is in the dataset without having to look at every row.

In [ ]:
df['brand'].unique()

array(['Yum Yum', 'Indomie'], dtype=object)

In [ ]:
df['style'].unique()

array(['cup', 'pack'], dtype=object)

In [ ]:
df['rating'].unique()

array([4. , 3.5, 5. ])

In [ ]:
df.nunique()

brand     2
style     2
rating    3
dtype: int64

In [ ]:
df['rating'].nunique()

3

## Group By

We can also aggregate the data similar to how we use ***GROUP BY*** in SQL.

Here, we're going to calculate the average rating for each brand and style:

In [ ]:
# For each combination of brand
df.groupby('brand').mean()

# SELECT brand, AVG(*)
# from df
# GROUP BY brand

rating
brand          
Indomie     4.5
Yum Yum     4.0

In [ ]:
# For each style
df.groupby('style').mean()

rating
style          
cup    3.833333
pack   5.000000

**Practice: What would be the groupby statement for the average rating for each combination of brand and style?**

In [ ]:
# Your code here
df.groupby(['brand', 'style']).mean()
# SQL
# SELECT brand, style, AVG(rating)
# from df
# GROUP BY brand, style

rating
brand   style        
Indomie cup       3.5
        pack      5.0
Yum Yum cup       4.0

Notice that the GroupBy function turns every group into an index. We can undo that by resetting the index after running GroupBy.

# Visualizing Data (Optional)

We're going to explore three ways to create charts in Python
1. Pandas
2. Matplotlib
3. Seaborn

Depending on what kind of chart you want to make, and how customized you want to make it, you will choose one of these three (most of the time)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

Using Pandas

In [ ]:
df = pd.DataFrame({
    'name':['john','mary','peter','jeff','bill','lisa','jose'],
    'age':[23,78,22,19,45,33,20],
    'gender':['M','F','M','M','M','F','M'],
    'state':['california','dc','california','dc','california','texas','texas'],
    'num_children':[2,0,0,3,2,1,4],
    'num_pets':[5,1,0,5,2,2,3]
})

df

In [ ]:
df.plot(kind='bar')  # will automatically plot the numerical values

In [ ]:
df.plot(kind='bar', x='name', y='age')

In [ ]:
df.plot(kind='bar', x='name', y=['age', 'num_children'])

Using Matplotlib - more control

In [ ]:
def function1(num1, num2):
    sum = num1 + num2
    return sum, num1

In [ ]:
fig, ax = plt.subplots(figsize=(12, 6))

ax.bar(df['name'], df['age'])

ax.set_xlabel('Name of Person', fontsize=20)
ax.set_ylabel('Age of Person', fontsize=20)

ax.set_title('Age of Each Person: Visualized', fontsize=20)

Using Seaborn

In [ ]:
sns.barplot(data=df, x='name', y='age')

Summarizing age by gender and state using bar plots


In [ ]:
sns.barplot(data=df, x='state', y='age', hue='gender')

In [ ]:
# Seaborn bar plots have whiskers, we can remove them
sns.barplot(data=df, x='state', y='age', hue='gender', errwidth=0)

**Practice - Can you visualize some of the data you brought in yesterday from Wikipedia?**

In [ ]:
# Your code here.


# Resources
- The world's most popular Python podcast: [Talk Python to Me](https://talkpython.fm)
- The definitive book on Pandas: [Python for Data Analysis](https://wesmckinney.com/book/)
- The BEST Introduction to Applied Statistics: [StatQuest - Joshua Starmer](https://www.youtube.com/playlist?list=PLblh5JKOoLUK0FLuzwntyYI10UQFUhsY9)
- Working with files in Google Colab: [Link](https://colab.research.google.com/notebooks/io.ipynb#scrollTo=p2E4EKhCWEC5)